#!/bin/bash
#SBATCH -n 4
#SBATCH -N 1
#SBATCH -D /tmp
#SBATCH -J task_e_lora
#SBATCH -t 2-00:00
#SBATCH -p mlow
#SBATCH -q masterlow
#SBATCH --mem 57344
#SBATCH --gres gpu:1
#SBATCH -o /ghome/group07/MCV-C5-Group7/Week5/task_e/output/%x_%u_%j.out
#SBATCH -e /ghome/group07/MCV-C5-Group7/Week5/task_e/output/%x_%u_%j.err

# ── Tunable parameters ──────────────────────────────────────────────────────
# Percentage of Task D augmented data to include in training (0 = no augmentation)
AUG_FRACTION=50

# Path to the augmented dataset generated by Task D (contains annotations.json + images/)
AUG_DATASET=/ghome/group07/MCV-C5-Group7/Week5/task_d/augmented_dataset/110919

# ViT encoder checkpoint from Task1_ft
VIT_CHECKPOINT=/ghome/group07/MCV-C5-Group7/Week4/Task1_ft/results/vit_gpt2_vit_ft_gpt_frozen_enc4L_frozen/109481/weights/best_model.pt

# To resume a previous run, set RESUME_DIR to that job's results directory.
# Leave empty to start fresh.
# Example: RESUME_DIR=/ghome/group07/MCV-C5-Group7/Week5/task_e/results/qwen_lora_2b_Aug50pct/110805
RESUME_DIR=""
# ────────────────────────────────────────────────────────────────────────────

sleep 5
source /ghome/group07/miniconda3/etc/profile.d/conda.sh
conda activate c5clean

export LD_LIBRARY_PATH="$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

mkdir -p /ghome/group07/MCV-C5-Group7/Week5/task_e/output

RESUME_ARG=""
if [ -n "${RESUME_DIR}" ]; then
    RESUME_ARG="--resume-dir ${RESUME_DIR}"
fi

python /ghome/group07/MCV-C5-Group7/Week5/task_e/main.py \
    --vit-checkpoint "$VIT_CHECKPOINT" \
    --aug-fraction   ${AUG_FRACTION} \
    --aug-dataset    "${AUG_DATASET}" \
    ${RESUME_ARG}
